### ISSUE TITLE
Error with Replay Buffer

### ISSUE THREAD

**Issue by JanoschMenke** [schwallergroup/saturn#4]
Hi Jeff,

When trying to run Saturn I get the following error message for the replay buffer.

```
Traceback (most recent call last):
  File "/app/saturn/saturn.py", line 76, in <module>
    reinforcement_learning_agent = ReinforcementLearningAgent(
  File "/app/saturn/goal_directed_generation/reinforcement_learning.py", line 66, in __init__
    self.oracle = self.replay_buffer.prepopulate_buffer(self.oracle)
  File "/app/saturn/experience_replay/replay_buffer.py", line 138, in prepopulate_buffer
    rewards = np.empty((len(oracle), len(mols)))
TypeError: object of type 'Oracle' has no len()
```

This is the part of the config
```
    "experience_replay": {
      "memory_size": 100,  
      "sample_size": 10, 
      "smiles": []  
   ```
   
   Do you know what could cause this?

**Comment by GuoJeff** [comment]
Hi Janosch, 

Sorry for this, it is a mistake in an attribute calling in the function. I just pushed a change.

**Comment by JanoschMenke** [comment]
Awesome thanks for the quick fix.

**Comment by GuoJeff** [comment]
Closing for now.
